name: Update origin trials

on:
  push:
    branches: [main]
  schedule:
    # Run once a week.
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        if: ${{ github.event_name == 'push' }}
        run: npm ci

      - name: Run the update-origin-trials script
        if: ${{ github.event_name != 'push' }}
        run: node additional-data/scripts/update-origin-trials.js

      - name: Commit changes
        if: ${{ github.event_name != 'push' }}
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Refresh OTs" --allow-empty
          git push origin main
