name: Update Interop data

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run the update-interop script
        run: node additional-data/scripts/update-interop.js

      - name: Commit changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Refresh Interop data" --allow-empty
          git push origin main
