name: Update Use Counters data

on:
  schedule:
    - cron: '0 5 */7 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run the update-use-counters script
        run: node additional-data/scripts/update-use-counters.js

      - name: Commit changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Refresh Use Counters data" --allow-empty
          git push origin main
